services:
  fach:
    image: node:18-alpine
    container_name: fachinformatiker-azubi-de
    restart: unless-stopped
    working_dir: /app
    command: npm run serve
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    ports:
      - 8002:3000
